swagger: '2.0'
info:
  version: '0.1.0'
  title: Email API
  description: An API to handle templates and send an email from a template
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /tags:
    post:
      tags:
        - tag
      summary: Create a tag
      operationId: createTag
      consumes:
        - application/json
      parameters:
        - name: tag
          in: body
          description: Create a tag
          schema:
            $ref: '#/definitions/Tag'
          required: true
      responses:
        '201':
          description: Tag created
          schema:
            type: object
    get:
      tags:
        - tag
      summary: Get tags list
      operationId: getTags
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            title: Tags
            type: array
            items:
              $ref: '#/definitions/Tag'

#  /tags/{tagId}:
#    put:
#      tags:
#        - tag
#      summary: Update a tag
#      operationId: updateTag
#      parameters:
#        - name: tagId
#          in: path
#          type: string
#          description: tag ID
#          required: true
#        - name: tag
#          in: body
#          description: Tag
#          schema:
#            $ref: '#/definitions/Tag'
#          required: true
#      responses:
#        '200':
#          description: Tag updated
#
#    patch:
#      tags:
#        - tag
#      summary: Update name of a tag
#      operationId: updateTagName
#      parameters:
#        - name: tagId
#          in: path
#          type: string
#          description: tag ID
#          required: true
#        - name: tagName
#          in: body
#          description: Name of tag
#          type: string
#          required: true
#      responses:
#        '200':
#          description: Name of tag updated
#
#    delete:
#      tags:
#        - tag
#      summary: Delete a tag
#      operationId: deleteTag
#      parameters:
#        - name: tagId
#          in: path
#          type: string
#          description: tag ID
#          required: true
#      responses:
#        '200':
#          description: Tag deleted

  /templates:
    post:
      tags:
        - template
      summary: Create a template
      operationId: createTemplate
      consumes:
        - application/json
      parameters:
        - name: template
          in: body
          description: Create a template
          required: true
          schema:
            $ref: '#/definitions/Template'
      responses:
        '201':
          description: Template created
          schema:
            type: object
    get:
      tags:
        - template
      summary: Get templates list
      operationId: getTemplates
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            title: Templates
            type: array
            items:
              $ref: '#/definitions/Template'

  /emails:
    post:
      tags:
        - email
      summary: Create a tag
      operationId: createEmail
      consumes:
        - application/json
      parameters:
        - name: email
          in: body
          description: Create a email
          required: true
          schema:
            $ref: '#/definitions/Email'
      responses:
        '201':
          description: Email created
          schema:
            type: object
    get:
      tags:
        - email
      summary: Get emails list
      operationId: getEmails
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            title: Emails
            type: array
            items:
              $ref: '#/definitions/Email'

definitions:
  Tag:
    type: object
    properties:
      url:
        type: string
      name:
        type: string
#      templates:
#        type: array
#        items:
#          $ref: '#/definitions/Template'

  Template:
    type: object
    properties:
      url:
        type: string
      name:
        type: string
#      tags:
#        type: array
#        items:
#          $ref: '#/definitions/Tag'
#      parameters:
#        type: array
#        items:
#          type: string
      body:
        type: string

  Email:
    type: object
    properties:
      from:
        type: string
      to:
        type: string
      subject:
        type: string
      body:
        type: string