version: '2'
services:
  mysql:
    build: ./mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3305:3306"
  phpmyadmin:
    build: ./phpmyadmin
    environment:
     - MYSQL_ROOT_PASSOWRD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db
