version: '2'
services:
  mysql:
    build: ./mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3305:3306"
  phpmyadmin:
    build: ./phpmyadmin
    environment:
     - MYSQL_ROOT_PASSOWRD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db
  spring:
    build: ./java
    entrypoint: ["/opt/wait_for_it.sh", "mysql:3306", "--", "java","-jar","/home/swagger-spring-1.0.0.jar"]
    environment:
     - spring_datasource_url=jdbc:mysql://mysql:3306/data_email?useSSL=false
    ports:
     - "8080:8080"
