swagger: '2.0'
info:
  version: 1.0.0
  title: microservice-email
  description: >
    Microservice to handle templates and send an email from a template.


    Find source code of this API
    [here](https://github.com/PestaKit/microservice-email)
host: 'localhost:8080'
basePath: /email
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /templates:
    get:
      tags:
        - template
      summary: Get templates list
      operationId: getTemplatesList
      responses:
        '200':
          description: Get templates List
          schema:
            title: Templates
            type: array
            items:
              $ref: '#/definitions/Template'
        '404':
          description: Template not found
  '/templates/{templateId}':
    get:
      tags:
        - template
      summary: Get a template
      operationId: getTemplate
      parameters:
        - name: templateId
          in: path
          type: string
          description: ID of template
          required: true
      responses:
        '200':
          description: Get a template
          schema:
            title: Template
            $ref: '#/definitions/Template'
        '400':
          description: Invalid template ID supplied
        '404':
          description: Template not found
definitions:
  Template:
    type: object
    properties:
      url:
        type: string
      name:
        type: string
      tags:
        type: array
        items:
          type: string
      parameters:
        type: array
        items:
          type: string
      body:
        type: string
  Email:
    type: object
    properties:
      form:
        type: string
      to:
        type: string
      subject:
        type: string
      body:
        type: string